### PR TITLE
Fix #5: Add missing default Obsidian callout types

### LINKED ISSUE #5: "Note" default Obsidian callout not found in the plugin's callout list (Windows / Linux)
Plugin does not list the "Note" callout in the Obsidian default callouts list:
image
(Obsidian default Note callout)

image
(message from the plugin)

image
(plugin callout list)

👀 Observed on both Windows11 and Linux (Manjaro).
📦 Obsidian version 1.2.8.

### PR DESCRIPTION
**Pull request by RaviOnline**
Update `callout-fallback-obsidian.json` to include missing default `note` and `question` callout types.

### CODE REVIEW

**Comment by RaviOnline** [comment]
Review request @eth-p

**Comment by marblewraith** [comment]
MERGE THIS PR ALREADY!

The fact Github supports callouts now...

> [!NOTE]
>
> But the note type *cannot* be seen or manipulated by this plugin is most annoying.

**Comment by eth-p** [comment]
Hi @RaviOnline,

Thank you for adding those two missing options to the plugin! The changes look good to me, and they will be merged shortly after this comment.

**Comment by eth-p** [comment]
Hi @marblewraith,

While I appreciate your frustration with the lack of progress being made from my end of things, directing me to merge a pull request with capitalized text is a rather hostile way to bring something to my attention. A significantly more terse and friendly approach would have been to simply ask, "@eth-p, are there any updates on this?"

**Pull request merged**
